"""Declarative ZackOS LFS installer profiles."""
from dataclasses import dataclass, asdict
import json


CHOICES = {
    "base": ("lfs",),
    "libc": ("glibc", "musl"),
    "package_manager": ("apt", "emerge", "xbps", "nix"),
    "init": ("sysvinit", "runit", "openrc", "systemd"),
    "bootloader": ("grub", "limine", "systemd-boot", "refind"),
    "desktop": ("none", "i3", "plasma-x11", "hyprland"),
    "persistence": ("overlay", "none"),
}


@dataclass(frozen=True)
class InstallerProfile:
    """The complete requested ZackOS composition.

    The base is deliberately fixed to LFS. Package manager, init, libc,
    bootloader, and desktop are components, not distro replacements.
    """
    base: str = "lfs"
    libc: str = "glibc"
    package_manager: str = "nix"
    init: str = "sysvinit"
    bootloader: str = "grub"
    desktop: str = "i3"
    persistence: str = "overlay"

    def validate_choices(self):
        errors = []
        for field, choices in CHOICES.items():
            value = getattr(self, field)
            if value not in choices:
                errors.append(f"{field}={value!r} is not one of: {', '.join(choices)}")
        # libc must be selected before package/provider builds in real builds.
        if self.desktop == "hyprland" and self.libc == "musl":
            errors.append("hyprland+musl is experimental and is not enabled yet")
        return errors

    def to_toml(self):
        lines = ["# Generated by ZackInstaller; do not edit during installation."]
        for key, value in asdict(self).items():
            lines.append(f'{key} = {json.dumps(value)}')
        return "\n".join(lines) + "\n"

    def to_dict(self):
        return asdict(self)
